server:
  port: 8302
  
spring:
  application:
    name: eureka-discovery-service

eureka:
  instance: 
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:8302/eureka/